function write_vtk(vertex, face, filename, verbose)
% write_vtk - write mesh data to a VTK file.
%
%   write_vtk(vertex, face, filename, verbose) writes the mesh defined by 
%   the vertices and faces to a VTK file.
%
%   'vertex' is a 3 x N (or N x 3) array specifying vertex positions.
%   'face' is a 3 x M (or M x 3) array specifying mesh connectivity.
if nargin < 4
    verbose = 0;
end

% Ensure vertex is in 3 x N format.
if size(vertex,1) ~= 3
    vertex = vertex';
end

% Ensure face is in 3 x M format.
if size(face,1) ~= 3
    face = face';
end

fid = fopen(filename, 'w');
if fid == -1
    error('Can''t open file for writing.');
    return;
end

% Write header information
fprintf(fid, '# vtk DataFile Version 3.0\n');
fprintf(fid, 'VTK file generated by write_vtk.m\n');
fprintf(fid, 'ASCII\n');
fprintf(fid, 'DATASET POLYDATA\n');

% Write vertex (point) data
nvert = size(vertex, 2);
fprintf(fid, 'POINTS %d float\n', nvert);
for i = 1:nvert
    fprintf(fid, '%f %f %f\n', vertex(1,i), vertex(2,i), vertex(3,i));
end

% Write face (polygon) data
nface = size(face, 2);
fprintf(fid, 'POLYGONS %d %d\n', nface, nface * 4);
for i = 1:nface
    % VTK uses 0-indexing; subtract 1 from each vertex index
    fprintf(fid, '3 %d %d %d\n', face(1,i)-1, face(2,i)-1, face(3,i)-1);
end

fclose(fid);

if verbose
    fprintf('VTK file written to: %s\n', filename);
end

return
